### PR TITLE
TAKT-5626 Exports dhtmlx names for google CC

### PR DESCRIPTION
**Pull request by schell**

### CODE REVIEW

**Comment by mightybyte** [comment]
What did you have to do to that JS blob?

**Comment by schell** [comment]
I was just writing that in the comments! I had to export all identifiers that are referenced in downstream code. That ended up not being many (dhx, dhx4, dhtmlxEvents) but i had to deconstruct that blob and put the exports in the correct places which was a little tricky.
https://developers.google.com/closure/compiler/docs/api-tutorial3#export

**Comment by mightybyte** [comment]
Can you document that somewhere, so that if we want to upgrade to a newer version of the upstream lib in the future we'll know how to duplicate your work?  Perhaps in README.md.

**Comment by schell** [comment]
Documented in takt-core's readme.

**Review by mightybyte — APPROVED** [review]
Great, thanks!

**Pull request merged**
